songchan0321/koguma

build.gradle, src/main/java/com/fiveguys/koguma/config/RedisConfig.java, src/main/java/com/fiveguys/koguma/data/dto/AlertDTO.java, src/main/java/com/fiveguys/koguma/service/common/AlertService.java, src/main/java/com/fiveguys/koguma/service/common/AlertServiceImpl.java, src/test/java/com/fiveguys/koguma/common/AlertApplicationTests.java
AlertService, AlertService Test 완료
RedisConfig 설정
- Redis 서버 구축 시 주소 변경 필요
- Redis 알림 읽기 기능(readAlert) 추후 기능 개선 리펙토링 예정
=> feat: 알림 구현

build.gradle, src/main/java/com/fiveguys/koguma/controller/TestController.java
=> fix : java version 11 -> 17, TestController add

src/main/java/com/fiveguys/koguma/controller/CommentRestController.java, src/main/java/com/fiveguys/koguma/controller/PostRestController.java, src/main/java/com/fiveguys/koguma/data/dto/CommentDTO.java, src/main/java/com/fiveguys/koguma/data/dto/PostDTO.java, src/main/java/com/fiveguys/koguma/data/entity/Comment.java, src/main/java/com/fiveguys/koguma/repository/post/PostRepository.java, src/main/java/com/fiveguys/koguma/service/post/CommentService.java, src/main/java/com/fiveguys/koguma/service/post/CommentServiceImpl.java, src/main/java/com/fiveguys/koguma/service/post/PostService.java, src/main/java/com/fiveguys/koguma/service/post/PostServiceImpl.java, src/test/java/com/fiveguys/koguma/post/PostApplicationTests.java
Post/Comment RestController 구현 및 postman 테스트 완료
2023.12.07 / 09:30 / HSC
=> feat : Post/Comment RestController 구현 및 postman 테스트 완료

src/main/java/com/fiveguys/koguma/config/CorsConfig.java, src/main/java/com/fiveguys/koguma/config/SecurityConfig.java, src/main/java/com/fiveguys/koguma/controller/AuthRestController.java, src/main/java/com/fiveguys/koguma/controller/ImageRestController.java, src/main/java/com/fiveguys/koguma/controller/LocationRestController.java, src/main/java/com/fiveguys/koguma/controller/ProductRestController.java, src/main/java/com/fiveguys/koguma/controller/ReviewRestController.java, src/main/java/com/fiveguys/koguma/service/common/AuthService.java, src/main/java/com/fiveguys/koguma/service/common/AuthServiceImpl.java, src/main/java/com/fiveguys/koguma/service/common/ImageService.java, src/main/java/com/fiveguys/koguma/service/common/ImageServiceImpl.java, src/main/java/com/fiveguys/koguma/service/member/MemberService.java, src/main/java/com/fiveguys/koguma/service/member/MemberServiceImpl.java, src/main/java/com/fiveguys/koguma/util/filter/JwtRequestFilter.java
=> feat: corsConfig 설정 

src/main/java/com/fiveguys/koguma/controller/ReportRestController.java, src/main/java/com/fiveguys/koguma/data/dto/MemberDTO.java, src/test/java/com/fiveguys/koguma/member/MemberRelationshipApplicationTests.java
RegDate 추가
2023.12.14 / 18:14 / SIC
=> fix : MemberDTO 수정

src/main/java/com/fiveguys/koguma/controller/ClubRestController.java, src/main/java/com/fiveguys/koguma/service/club/ClubService.java, src/main/java/com/fiveguys/koguma/service/club/ClubServiceImpl.java
=> fix: ClubRestController 매개값 변경

build.gradle, src/main/java/com/fiveguys/koguma/controller/MemberRelationshipRestController.java, src/main/java/com/fiveguys/koguma/repository/member/MemberRelationshipRepository.java, src/main/java/com/fiveguys/koguma/service/member/MemberRelationshipService.java, src/main/java/com/fiveguys/koguma/service/member/MemberRelationshipServiceImpl.java
postman test 완료
2023.12.15 / 17:37 / SIC
=> feat : 차단 확인 서비스, 컨트롤러 추가

src/main/java/com/fiveguys/koguma/controller/ClubPostController.java, src/main/java/com/fiveguys/koguma/controller/ClubRestController.java, src/main/java/com/fiveguys/koguma/controller/ImageRestController.java, src/main/java/com/fiveguys/koguma/data/dto/ClubMemberDTO.java, src/main/java/com/fiveguys/koguma/data/dto/CreateClubDTO.java, src/main/java/com/fiveguys/koguma/data/dto/club/AddClubDTO.java, src/main/java/com/fiveguys/koguma/repository/club/ClubPostRepository.java, src/main/java/com/fiveguys/koguma/service/club/ClubPostService.java, src/main/java/com/fiveguys/koguma/service/club/ClubServiceImpl.java
=> fix: clubcontroller 매개값 변경  추가  매개값 변경

src/main/java/com/fiveguys/koguma/controller/MemberRelationshipRestController.java
불필요 주석 삭제
2023.12.21 / 18:25 / SIC
=> refactor : 주석 바꿈

src/main/java/com/fiveguys/koguma/controller/ReviewRestController.java
=> fix: 리뷰 메소드 추가

src/main/java/com/fiveguys/koguma/controller/ProductRestController.java, src/main/java/com/fiveguys/koguma/controller/ReviewRestController.java, src/main/java/com/fiveguys/koguma/repository/common/LikeFilterAssociationRepository.java, src/main/java/com/fiveguys/koguma/service/common/LikeFilterAssociationService.java, src/main/java/com/fiveguys/koguma/service/common/LikeFilterAssociationServiceImpl.java, src/main/java/com/fiveguys/koguma/service/member/MemberServiceImpl.java, src/main/java/com/fiveguys/koguma/service/product/ReviewServiceImpl.java
리뷰등록 / 좋아요 누른 회원에게 가격인하
/ 가격제안 알림
=> 상품 관련 알림 추가

src/main/java/com/fiveguys/koguma/repository/common/LikeFilterAssociationRepository.java
=> left join 중복 조회 해결

src/main/generated/com/fiveguys/koguma/data/entity/QClub.java, src/main/java/com/fiveguys/koguma/controller/ClubRestController.java, src/main/java/com/fiveguys/koguma/data/dto/club/ListClubByCategoryDTO.java, src/main/java/com/fiveguys/koguma/data/entity/Club.java, src/main/java/com/fiveguys/koguma/repository/club/ClubMemberRepository.java, src/main/java/com/fiveguys/koguma/repository/club/ClubRepository.java, src/main/java/com/fiveguys/koguma/service/club/ClubMeetUpServiceImpl.java, src/main/java/com/fiveguys/koguma/service/club/ClubServiceImpl.java
=> fix: club list 조회시 ClumMember count OneToMany로 처리 로직 구성

src/main/java/com/fiveguys/koguma/repository/common/SmsRepository.java, src/main/java/com/fiveguys/koguma/service/common/SmsServiceImpl.java
=> fix : 휴대폰인증 오류 수정

src/main/java/com/fiveguys/koguma/controller/AuthRestController.java, src/main/java/com/fiveguys/koguma/service/member/MemberService.java, src/main/java/com/fiveguys/koguma/service/member/MemberServiceImpl.java
=> feat : 멤버 기본 이미지 넣기 위한 로직 수정

src/main/resources/application-prod.properties
=> fix: 카카오로그인 url 수정

src/main/generated/com/fiveguys/koguma/data/entity/QClubPost.java, src/main/java/com/fiveguys/koguma/controller/ClubPostController.java, src/main/java/com/fiveguys/koguma/data/dto/club/ClubPostDTO.java, src/main/java/com/fiveguys/koguma/data/entity/ClubPost.java, src/main/java/com/fiveguys/koguma/service/club/ClubPostCategoryImpl.java, src/main/java/com/fiveguys/koguma/service/club/ClubPostService.java
=> fix: ClubPost images 컬럼 추가로 인한 DTO 필드값 변경 및 서비스 로직 set추가

src/main/generated/com/fiveguys/koguma/data/entity/QClubComment.java, src/main/java/com/fiveguys/koguma/controller/ClubPostController.java, src/main/java/com/fiveguys/koguma/controller/ClubRestController.java, src/main/java/com/fiveguys/koguma/data/dto/club/ClubPostCommentDTO.java, src/main/java/com/fiveguys/koguma/data/dto/club/MeetUpStateDTO.java, src/main/java/com/fiveguys/koguma/data/entity/ClubComment.java, src/main/java/com/fiveguys/koguma/service/club/ClubServiceImpl.java
=> fix: ClubPost list 수정

src/main/java/com/fiveguys/koguma/service/member/MemberServiceImpl.java
타 회원 프로필 조회 시 사진도 볼 수 있게 수정함
2023.12.26 / 19:46 / SIC
=> refactor : getOtherMember 수정

src/main/java/com/fiveguys/koguma/controller/ClubPostController.java, src/main/java/com/fiveguys/koguma/data/entity/ClubPost.java, src/main/java/com/fiveguys/koguma/service/club/ClubPostService.java
=> fix: ClubPost addPost 수정 수정

src/main/generated/com/fiveguys/koguma/data/entity/QClubComment.java, src/main/java/com/fiveguys/koguma/controller/ClubPostController.java, src/main/java/com/fiveguys/koguma/controller/ClubRestController.java, src/main/java/com/fiveguys/koguma/data/dto/club/ClubPostCommentDTO.java, src/main/java/com/fiveguys/koguma/data/dto/club/ClubPostDTO.java, src/main/java/com/fiveguys/koguma/data/entity/ClubComment.java, src/main/java/com/fiveguys/koguma/repository/club/ClubCommentRepository.java, src/main/java/com/fiveguys/koguma/service/club/ClubPostService.java
=> fix: ClubPost Comment 추가 및 수정 수정

src/main/java/com/fiveguys/koguma/controller/PostRestController.java, src/main/java/com/fiveguys/koguma/data/dto/PostDTO.java, src/main/java/com/fiveguys/koguma/data/entity/Post.java, src/main/java/com/fiveguys/koguma/repository/common/QueryRepositoryImpl.java, src/main/java/com/fiveguys/koguma/repository/post/PostRepository.java, src/main/java/com/fiveguys/koguma/service/post/PostService.java, src/main/java/com/fiveguys/koguma/service/post/PostServiceImpl.java, src/test/java/com/fiveguys/koguma/post/PostApplicationTests.java
=> feat: 동네생활 리스트, 조회, 카테고리 조회에 이미지 추가

src/main/java/com/fiveguys/koguma/repository/common/QueryRepositoryImpl.java
=> fix: 동네생활 이미지 쿼리 중복제거
